# Section 1

# Project Data Cleaning and Aggregation

In [ ]:
import os, pandas as pd
from google.colab import drive
drive.mount('/content/drive/')
os.chdir('/content/drive/MyDrive/Opt Modeling/Project')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
os.listdir()

['Original EV Stations CO (Nov 7 2025).csv',
 'num_ev_incounties.csv',
 'zipcodes_co.csv',
 'highway_county.csv',
 'Project Ideas.gdoc',
 'final_ev_stations.csv',
 'charging_stations_per_county.csv',
 'needed_fastchargers.csv',
 'results_opt.csv',
 'experiment1.csv',
 'experiment2.csv',
 'experiment3.csv']

### 1. Initial Data Inspection of csv files that we found

In [ ]:
# Read files

electric_cars = pd.read_csv('num_ev_incounties.csv')
ev_charging_stations = pd.read_csv('Original EV Stations CO (Nov 7 2025).csv')
zip_codes = pd.read_csv('zipcodes_co.csv')
highways = pd.read_csv('highway_county.csv')

In [ ]:
electric_cars.head()

      county  ev cars
0      Adams    12251
1    Alamosa       94
2   Arapahoe    24377
3  Archuleta      164
4       Baca       10

In [ ]:
electric_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   county   65 non-null     object
 1   ev cars  65 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.1+ KB

In [ ]:
zip_codes.head()

     zip    city    county stateCode  population     state
0  80134  Parker   Douglas        CO       75383  Colorado
1  80013  Aurora  Arapahoe        CO       73870  Colorado
2  80015  Aurora  Arapahoe        CO       72841  Colorado
3  80016  Aurora  Arapahoe        CO       64842  Colorado
4  80219  Denver    Denver        CO       64696  Colorado

In [ ]:
zip_codes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   zip         535 non-null    int64
 1   city        535 non-null    object
 2   county      535 non-null    object
 3   stateCode   535 non-null    object
 4   population  535 non-null    int64
 5   state       535 non-null    object
dtypes: int64(2), object(4)
memory usage: 25.2+ KB

In [ ]:
ev_charging_stations.head()

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,...,RD Blends,RD Blends (French),RD Blended with Biodiesel,RD Maximum Biodiesel Level,NPS Unit Name,CNG Station Sells Renewable Natural Gas,LNG Station Sells Renewable Natural Gas,Maximum Vehicle Class,EV Workplace Charging,Funding Sources
0,ELEC,Denver International Airport - Canopy Airport ...,8100 Tower Rd,Located in the indoor valet and covered self-p...,Commerce City,CO,80022,NaN,303-574-9800,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LD,False,NaN
1,ELEC,New Belgium Brewing,500 Linden St,NaN,Fort Collins,CO,80524,NaN,970-221-0524,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LD,False,NaN
2,ELEC,City of Boulder - Municipal Service Center,5050 Pearl St,NaN,Boulder,CO,80301,NaN,NaN,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LD,False,NaN
3,ELEC,City of Boulder - Park Central Building,1739 Broadway,NaN,Boulder,CO,80302,NaN,NaN,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LD,False,NaN
4,ELEC,Tynan's Nissan,5811 S College Ave,NaN,Fort Collins,CO,80525,NaN,970-282-1400,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LD,False,NaN

In [ ]:
ev_charging_stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 75 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Fuel Type Code                           2700 non-null   object
 1   Station Name                             2700 non-null   object
 2   Street Address                           2700 non-null   object
 3   Intersection Directions                  808 non-null    object
 4   City                                     2700 non-null   object
 5   State                                    2700 non-null   object
 6   ZIP                                      2700 non-null   int64
 7   Plus4                                    0 non-null      float64
 8   Station Phone                            2559 non-null   object
 9   Status Code                              2700 non-null   object
 10  Expected Date                            0 non-null      float64
 11  Groups With Access Code                  2700 non-null   object
 12  Access Days Time                         2526 non-null   object
 13  Cards Accepted                           218 non-null    object
 14  BD Blends                                0 non-null      float64
 15  NG Fill Type Code                        0 non-null      float64
 16  NG PSI                                   0 non-null      float64
 17  EV Level1 EVSE Num                       11 non-null     float64
 18  EV Level2 EVSE Num                       2266 non-null   float64
 19  EV DC Fast Count                         465 non-null    float64
 20  EV Other Info                            0 non-null      float64
 21  EV Network                               2700 non-null   object
 22  EV Network Web                           2454 non-null   object
 23  Geocode Status                           2700 non-null   object
 24  Latitude                                 2700 non-null   float64
 25  Longitude                                2700 non-null   float64
 26  Date Last Confirmed                      2688 non-null   object
 27  ID                                       2700 non-null   int64
 28  Updated At                               2700 non-null   object
 29  Owner Type Code                          535 non-null    object
 30  Federal Agency ID                        15 non-null     float64
 31  Federal Agency Name                      15 non-null     object
 32  Open Date                                2688 non-null   object
 33  Hydrogen Status Link                     0 non-null      float64
 34  NG Vehicle Class                         0 non-null      float64
 35  LPG Primary                              0 non-null      float64
 36  E85 Blender Pump                         0 non-null      float64
 37  EV Connector Types                       2700 non-null   object
 38  Country                                  2700 non-null   object
 39  Intersection Directions (French)         0 non-null      float64
 40  Access Days Time (French)                0 non-null      float64
 41  BD Blends (French)                       0 non-null      float64
 42  Groups With Access Code (French)         2700 non-null   object
 43  Hydrogen Is Retail                       0 non-null      float64
 44  Access Code                              2700 non-null   object
 45  Access Detail Code                       112 non-null    object
 46  Federal Agency Code                      15 non-null     object
 47  Facility Type                            535 non-null    object
 48  CNG Dispenser Num                        0 non-null      float64
 49  CNG On-Site Renewable Source             0 non-null      float64
 50  CNG Total Compression Capacity           0 non-null      float64
 51  CNG Storage Capacity                     0 non-null      float64
 52  LNG On-Site Renewable Source             0 non-null      float64
 53  E85 Other Ethanol Blends                 0 non-null      float64
 54  EV Pricing                               402 non-null    object
 55  EV Pricing (French)                      0 non-null      float64
 56  LPG Nozzle Types                         0 non-null      float64
 57  Hydrogen Pressures                       0 non-null      float64
 58  Hydrogen Standards                       0 non-null      float64
 59  CNG Fill Type Code                       0 non-null      float64
 60  CNG PSI                                  0 non-null      float64
 61  CNG Vehicle Class                        0 non-null      float64
 62  LNG Vehicle Class                        0 non-null      float64
 63  EV On-Site Renewable Source              22 non-null     object
 64  Restricted Access                        2419 non-null   object
 65  RD Blends                                0 non-null      float64
 66  RD Blends (French)                       0 non-null      float64
 67  RD Blended with Biodiesel                0 non-null      float64
 68  RD Maximum Biodiesel Level               0 non-null      float64
 69  NPS Unit Name                            17 non-null     object
 70  CNG Station Sells Renewable Natural Gas  0 non-null      float64
 71  LNG Station Sells Renewable Natural Gas  0 non-null      float64
 72  Maximum Vehicle Class                    378 non-null    object
 73  EV Workplace Charging                    2700 non-null   bool
 74  Funding Sources                          7 non-null      object
dtypes: bool(1), float64(40), int64(2), object(32)
memory usage: 1.5+ MB

In [ ]:
# Check some values in colums
print(ev_charging_stations['Fuel Type Code'].unique())
print(ev_charging_stations['Status Code'].unique())
print(ev_charging_stations['EV Network'].unique())

['ELEC']
['E']
['Non-Networked' 'ChargePoint Network' 'AMPUP' 'Tesla' 'Tesla Destination'
 'EV Connect' 'Electrify America' 'Blink Network' 'OpConnect'
 'SHELL_RECHARGE' 'eVgo Network' 'EVMATCH' 'EVGATEWAY' 'CHARGELAB'
 'UNIVERSAL' 'FLASH' 'EVRANGE' '7CHARGE' 'CIRCLE_K' 'GRAVITI_ENERGY'
 'RED_E' 'TURNONGREEN' 'VIALYNK' 'EVBOLT' 'ZEFNET' 'NOODOE' 'LOOP' 'EVOKE'
 'FORD_CHARGE' 'FLO' 'AUTEL' 'FCN' 'RIVIAN_WAYPOINTS' 'RIVIAN_ADVENTURE'
 'POWERFLEX' 'MERCEDES_BENZ' 'CHAEVI' 'JULE' 'SWTCH' 'IONNA'
 'STAY_N_CHARGE' 'ELECTRIC_ERA' 'ENVIROSPARK']

### 2. Data Cleaning and Preprocessing

In [ ]:
# Delete unnecessary columns from ev_charging stations table
ev_charging_st_small = ev_charging_stations.drop(ev_charging_stations.columns[[0, 3, 5, 7, 8, 9, 10, 11, 13, 14, 15, 16, 20, 21, 22, 26, 28, 29, 73, 74]], axis=1)
ev_charging_st_small = ev_charging_st_small.drop(ev_charging_st_small.columns[12:53], axis=1)
ev_charging_st_small = ev_charging_st_small.drop(ev_charging_st_small.columns[[8, 12, 13]], axis=1)
ev_charging_st_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Station Name        2700 non-null   object
 1   Street Address      2700 non-null   object
 2   City                2700 non-null   object
 3   ZIP                 2700 non-null   int64
 4   Access Days Time    2526 non-null   object
 5   EV Level1 EVSE Num  11 non-null     float64
 6   EV Level2 EVSE Num  2266 non-null   float64
 7   EV DC Fast Count    465 non-null    float64
 8   Latitude            2700 non-null   float64
 9   Longitude           2700 non-null   float64
 10  ID                  2700 non-null   int64
dtypes: float64(5), int64(2), object(4)
memory usage: 232.2+ KB

In [ ]:
# NEED TO ADD COLUMN COUNTY in ev_charging_st_ small table

# 1. check zip codes and replace wrong
''' This are the zip codes that are either missing or error typo in the Stations df'''
#stations[stations['county'].isna()]['ZIP'].unique()
#array([84024-- should be 80424, 80523, 80529 -- should be 80528, 80477, 80165, 80201, 80511, 80497, 81502, 80429--should be 80249, 80309])

# replace the zip of 84024 to 80424in the stations dataframe
ev_charging_st_small.loc[ev_charging_st_small['ZIP'] == 84024, 'ZIP'] = 80424

# replace the zip of 80429 to 80249 in the stations dataframe
ev_charging_st_small.loc[ev_charging_st_small['ZIP'] == 80429, 'ZIP'] = 80249

# replace the zip of 80529 to 80528 in the stations dataframe
ev_charging_st_small.loc[ev_charging_st_small['ZIP'] == 80529, 'ZIP'] = 80528

In [ ]:
# 2. Merge two tables and add county column
final_ev_stations = pd.merge(ev_charging_st_small, zip_codes[['zip', 'county']], left_on='ZIP', right_on='zip', how='left')
# Drop the redundant 'zip' column from the merge
final_ev_stations = final_ev_stations.drop(columns=['zip'])
display(final_ev_stations.head())

,Station Name,Street Address,City,ZIP,Access Days Time,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count,Latitude,Longitude,ID,county
0,Denver International Airport - Canopy Airport ...,8100 Tower Rd,Commerce City,80022,24 hours daily; pay lot,18.0,9.0,1.0,39.843886,-104.771138,38522,Adams
1,New Belgium Brewing,500 Linden St,Fort Collins,80524,11am-8pm daily; for customer use only,NaN,4.0,NaN,40.593417,-105.068400,42529,Larimer
2,City of Boulder - Municipal Service Center,5050 Pearl St,Boulder,80301,24 hours daily; employee use only,1.0,1.0,NaN,40.024578,-105.232194,42542,Boulder
3,City of Boulder - Park Central Building,1739 Broadway,Boulder,80302,Drivers must bring their own J1772 cordset for...,2.0,1.0,NaN,40.014800,-105.279200,42543,Boulder
4,Tynan's Nissan,5811 S College Ave,Fort Collins,80525,Dealership business hours,NaN,1.0,NaN,40.505604,-105.078041,43021,Larimer

In [ ]:
# 3. Check column county
nan_county_count = final_ev_stations['county'].isna().sum()
print(f"Number of NaN values in the 'County' column: {nan_county_count}")

Number of NaN values in the 'County' column: 0

In [ ]:
# 4. Save final file with ev stations
final_ev_stations.to_csv('/content/drive/MyDrive/Opt Modeling/Project/final_ev_stations.csv', index=False)

### 3. Data Aggregation (create new DataFrame according the previous analysis)

In [ ]:
# NEED TO CALCULATE THE NUMBER OF LEVEL 2 AND E DC FAST CHARGERS IN STATIONS IN EACH COUNTY

# 1. Fill NaN values in charger count columns with 0 before summing
final_ev_stations['EV Level2 EVSE Num'] = final_ev_stations['EV Level2 EVSE Num'].fillna(0)
final_ev_stations['EV DC Fast Count'] = final_ev_stations['EV DC Fast Count'].fillna(0)

# 2. Group by county and sum the number of Level 2 and DC Fast charging stations, and count the total stations
charging_stations_per_county = final_ev_stations.groupby('county').agg(
    total_level2_chargers=('EV Level2 EVSE Num', 'sum'),
    total_dc_fast_chargers=('EV DC Fast Count', 'sum'),
    num_charging_stations=('ID', 'count') # Count the number of unique station IDs per county
).reset_index()

# 3. Convert counts to integer type as they represent whole numbers
charging_stations_per_county['total_level2_chargers'] = charging_stations_per_county['total_level2_chargers'].astype(int)
charging_stations_per_county['total_dc_fast_chargers'] = charging_stations_per_county['total_dc_fast_chargers'].astype(int)

# 4. Add a new column for total number of chargers
charging_stations_per_county['total_chargers'] = charging_stations_per_county['total_level2_chargers'] + charging_stations_per_county['total_dc_fast_chargers']

display(charging_stations_per_county.head())

,county,total_level2_chargers,total_dc_fast_chargers,num_charging_stations,total_chargers
0,Adams,340,95,164,435
1,Alamosa,12,12,11,24
2,Arapahoe,381,113,168,494
3,Archuleta,10,3,8,13
4,Bent,1,0,1,1

In [ ]:
# 5. Save final file with ev stations
charging_stations_per_county.to_csv('/content/drive/MyDrive/Opt Modeling/Project/charging_stations_per_county.csv', index=False)

In [ ]:
# look at highway table
highways.head()

  Highway      County   aprox mileage CDOT Region  Region
0    I-25  Las Animas              39   Southeast       2
1    I-25    Huerfano              30   Southeast       2
2    I-25      Pueblo              47   Southeast       2
3    I-25     El Paso              47   Southeast       2
4    I-25      Douglas             32     Central       1

In [ ]:
# find sum in mileage by county
highway_by_county = highways.groupby('County ', as_index=False)["aprox mileage"].sum()

In [ ]:
# DECIDED TO CONCENTRATE ONLY ON DC FAST CHARGERS PORTS ALLONG IMPORTANT HIGHWAYS

# 1. Deleted unnecessary columns from the charging_stations_per_county table
fastcharging_stations_per_county = charging_stations_per_county.drop(columns=['total_level2_chargers', 'total_chargers'])
fastcharging_stations_per_county.head()

      county  total_dc_fast_chargers  num_charging_stations
0      Adams                      95                    164
1    Alamosa                      12                     11
2   Arapahoe                     113                    168
3  Archuleta                       3                      8
4       Bent                       0                      1

In [ ]:
# 2. To represent corridor needs, we differentiated charger spacing by county. Front Range counties with higher traffic:
# Adams, Arapahoe, Denver, Douglas, and Boulder, were assigned one fast charger per 3 miles of highway.
# All other counties were assigned one charger per 10 miles

import math
demand = {}

for county, mileage in highway_by_county.values:
  if county in ['Adams', 'Arapahoe', 'Denver', 'Douglas', 'Boulder']:
    divisor = 3.0
  else:
    divisor = 10.0

  demand[county] = math.ceil(mileage / divisor)

In [ ]:
# 3. Create Demand Dataframe
demand = pd.DataFrame(list(demand.items()), columns=["County", "Demand"])
demand["County"] = demand["County"].str.strip()

In [ ]:
# 4. Merge Demand Dataframe with fastcharging_stations_per_county
demand = demand.merge(
    fastcharging_stations_per_county[['county', 'total_dc_fast_chargers']],
    left_on='County',
    right_on='county',
    how='inner'
)

In [ ]:
# 5. Determine how many fast chargers needed in each county
demand['Needed'] = demand['Demand'] - demand['total_dc_fast_chargers']
needed = (demand[demand['Needed'] > 0])[['County', 'Needed']]
needed

        County  Needed
3    Archuleta       2
4         Bent       4
8     Cheyenne       3
10    Costilla       4
16      Elbert       6
20    Gunnison       3
21    Huerfano       5
25        Lake       5
31     Mineral       2
37       Ouray       2
38        Park       6
39    Phillips       3
44       Routt       2
45    Saguache       4
46    San Juan       3
48      Teller       1
49  Washington       5
51        Yuma      13

In [ ]:
# 6. Save final file with needed fast chargers by county
needed_fast_chargers = needed
display(needed_fast_chargers.head())
needed_fast_chargers.to_csv('/content/drive/MyDrive/Opt Modeling/Project/needed_fastchargers.csv', index=False)

       County  Needed
3   Archuleta       2
4        Bent       4
8    Cheyenne       3
10   Costilla       4
16     Elbert       6

# Section 2

# Optimization Model

### 1. Set up and import Gurobi

In [ ]:
!pip install gurobipy

import gurobipy as gp
from gurobipy import GRB

Requirement already satisfied: gurobipy in /usr/local/lib/python3.12/dist-packages (13.0.0)

### 2. Data Entry

In [ ]:
counties = [
    "Archuleta","Bent","Cheyenne","Costilla","Elbert","Gunnison","Huerfano",
    "Lake","Mineral","Ouray","Park","Phillips","Routt","Saguache",
    "San Juan","Teller","Washington","Yuma"
]

needed = {
    "Archuleta":2, "Bent":4, "Cheyenne":3, "Costilla":4, "Elbert":6,
    "Gunnison":3, "Huerfano":5, "Lake":5, "Mineral":2, "Ouray":2,
    "Park":6, "Phillips":3, "Routt":2, "Saguache":4,
    "San Juan":3, "Teller":1, "Washington":5, "Yuma":13
}

# Example regions (replace with your real classification)
regions = {
    "Western": ["Archuleta","Gunnison","Ouray","San Juan","Routt"],
    "Southern": ["Costilla","Huerfano","Saguache"],
    "Plains" : ["Bent","Cheyenne","Phillips","Washington","Yuma"],
    "Central": ["Elbert","Lake","Park","Mineral","Teller"]
}

cost_per_charger = 900000   # $ this is the cost per one charging station with one charger port
budget = 57100000           # $ NEVI program budget


# Region fairness (example: each region must get at least 10% of spend)
min_region_percent = 0.10

### 3. Set up the Linear Programming Model

In [ ]:
# ----------------------------
# MODEL
# ----------------------------
m = gp.Model("Colorado_EV_Planning")

# DECISION VARIABLES: x[c] = number of fast chargers built in county c
x = m.addVars(counties, vtype=GRB.INTEGER, name="x", lb=0)


# OBJECTIVE FUNCTION: maximize satisfied demand
m.setObjective(gp.quicksum(x[c] for c in counties), GRB.MAXIMIZE)


# ============================
# CONSTRAINT 1: Budget
# ============================

m.addConstr(gp.quicksum(cost_per_charger * x[c]
                        for c in counties) <= budget, "Budget")


# ============================
# CONSTRAINT 2: County minimum and maximum
# (example: at least 0, at most the demand)
# ============================

for c in counties:
    m.addConstr(x[c] <= needed[c], name=f"MaxInCounty[{c}]")
    m.addConstr(x[c] >= 0, name=f"MinInCounty[{c}]")


# ============================
# CONSTRAINT 3: Regional fairness constraints
# Each region must receive at least a fraction of total investment
# ============================

total_spend = gp.quicksum(cost_per_charger * x[c] for c in counties)

for r, rcounties in regions.items():
    m.addConstr(
        gp.quicksum(cost_per_charger * x[c] for c in rcounties)
        >= min_region_percent * total_spend,
        name=f"RegionMinSpend[{r}]"
    )

# ============================
# CONSTRAINT 4: County fairness constraints
# Each county must receive at least one charging station
# ============================

m.addConstrs((x[c] >= 1 for c in counties), name="AtLeastOne")

{'Archuleta': <gurobi.Constr *Awaiting Model Update*>,
 'Bent': <gurobi.Constr *Awaiting Model Update*>,
 'Cheyenne': <gurobi.Constr *Awaiting Model Update*>,
 'Costilla': <gurobi.Constr *Awaiting Model Update*>,
 'Elbert': <gurobi.Constr *Awaiting Model Update*>,
 'Gunnison': <gurobi.Constr *Awaiting Model Update*>,
 'Huerfano': <gurobi.Constr *Awaiting Model Update*>,
 'Lake': <gurobi.Constr *Awaiting Model Update*>,
 'Mineral': <gurobi.Constr *Awaiting Model Update*>,
 'Ouray': <gurobi.Constr *Awaiting Model Update*>,
 'Park': <gurobi.Constr *Awaiting Model Update*>,
 'Phillips': <gurobi.Constr *Awaiting Model Update*>,
 'Routt': <gurobi.Constr *Awaiting Model Update*>,
 'Saguache': <gurobi.Constr *Awaiting Model Update*>,
 'San Juan': <gurobi.Constr *Awaiting Model Update*>,
 'Teller': <gurobi.Constr *Awaiting Model Update*>,
 'Washington': <gurobi.Constr *Awaiting Model Update*>,
 'Yuma': <gurobi.Constr *Awaiting Model Update*>}

### 4. Results

In [ ]:
# Solve
m.optimize()

# Print results
print("\nOptimal number of charging stations with one fast charger to build per county:\n")

print(f"{'County':<15}{'Stations':<10}{'Cost':<15} \n")
for c in counties:
    print(f"{c:<15}{int(x[c].X):<10}${x[c].X * cost_per_charger:,.0f}")

print(f"\nTotal number of charging stations with one fast charger to build: {m.objVal:,.0f}")
print(f"Total cost of building charging stations: $ {m.objVal * cost_per_charger:,.0f}")

# Prepare data for table to save
results_data = []
for c in counties:
    optimized_chargers = x[c].X
    county_demand = needed[c]
    county_total_cost = optimized_chargers * cost_per_charger
    results_data.append({
        "County": c,
        "Demand": county_demand,
        "Optimized Chargers": optimized_chargers,
        "Total Cost": county_total_cost
    })

results_df = pd.DataFrame(results_data)

Gurobi Optimizer version 13.0.0 build v13.0.0rc1 (linux64 - "Ubuntu 22.04.4 LTS")

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 59 rows, 18 columns and 144 nonzeros (Max)
Model fingerprint: 0x0a469402
Model has 18 linear objective coefficients
Variable types: 0 continuous, 18 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 9e+05]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 6e+07]
Presolve removed 55 rows and 14 columns
Presolve time: 0.00s
Presolved: 4 rows, 4 columns, 16 nonzeros
Variable types: 0 continuous, 4 integer (0 binary)
Found heuristic solution: objective 30.0000000
Found heuristic solution: objective 40.0000000
Found heuristic solution: objective 50.0000000

Root relaxation: objective 6.344444e+01, 4 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   63.44444    0    1   50.00000   63.44444  26.9%     -    0s
H    0     0                      63.0000000   63.44444  0.71%     -    0s
     0     0   63.44444    0    1   63.00000   63.44444  0.71%     -    0s

Explored 1 nodes (4 simplex iterations) in 0.03 seconds (0.00 work units)
Thread count was 2 (of 2 available processors)

Solution count 4: 63 50 40 30

Optimal solution found (tolerance 1.00e-04)
Best objective 6.300000000000e+01, best bound 6.300000000000e+01, gap 0.0000%

Optimal number of charging stations with one fast charger to build per county:

County         Stations  Cost

Archuleta      2         $1,800,000
Bent           4         $3,600,000
Cheyenne       1         $900,000
Costilla       4         $3,600,000
Elbert         6         $5,400,000
Gunnison       3         $2,700,000
Huerfano       5         $4,500,000
Lake           5         $4,500,000
Mineral        2         $1,800,000
Ouray          2         $1,800,000
Park           6         $5,400,000
Phillips       1         $900,000
Routt          2         $1,800,000
Saguache       4         $3,600,000
San Juan       3         $2,700,000
Teller         1         $900,000
Washington     1         $900,000
Yuma           11        $9,900,000

Total number of charging stations with one fast charger to build: 63
Total cost of building charging stations: $ 56,700,000

In [ ]:
# Save Results DF
results_df.to_csv('/content/drive/MyDrive/Opt Modeling/Project/results_opt.csv', index=False)

In [ ]:
import folium

# Calculate approximate centroids for each county using the final_ev_stations DataFrame
# This DataFrame already contains 'Latitude', 'Longitude', and 'county'
county_centroids = final_ev_stations.groupby('county')[['Latitude', 'Longitude']].mean().reset_index()

# Merge the optimization results with the county centroids
map_data = results_df.merge(county_centroids, left_on='County', right_on='county', how='left')

# Drop the redundant 'county' column from the merge if it exists
if 'county' in map_data.columns:
    map_data = map_data.drop(columns=['county'])

display(map_data.head())

      County  Demand  Optimized Chargers  Total Cost   Latitude   Longitude
0  Archuleta       2                 2.0   1800000.0  37.341872 -106.928851
1       Bent       4                 4.0   3600000.0  38.083821 -102.952563
2   Cheyenne       3                 1.0    900000.0  38.763989 -102.790896
3   Costilla       4                 4.0   3600000.0  37.423925 -105.431613
4     Elbert       6                 6.0   5400000.0  39.353452 -104.529605

In [ ]:
# Create a base map of Colorado
m = folium.Map(location=[39.5, -105.5], zoom_start=7)

# Add markers for each county with optimized chargers
for idx, row in map_data.iterrows():
    if pd.notna(row['Latitude']) and pd.notna(row['Longitude']):
        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            popup=f"<b>County:</b> {row['County']}<br>" +
                  f"<b>Demand:</b> {row['Demand']}<br>" +
                  f"<b>Optimized Chargers:</b> {int(row['Optimized Chargers'])}<br>" +
                  f"<b>Cost:</b> ${row['Total Cost']:,}",
            icon=folium.Icon(color='green' if row['Optimized Chargers'] > 0 else 'red')
        ).add_to(m)

# Display the map
m

# Section 3

# Numerical Experiments and Results

### 1. Scenario for much higher demand (15%)

In [ ]:
import math

# ----------------------------
# DATA
# ----------------------------

counties = [
    "Archuleta","Bent","Cheyenne","Costilla","Elbert","Gunnison","Huerfano",
    "Lake","Mineral","Ouray","Park","Phillips","Routt","Saguache",
    "San Juan","Teller","Washington","Yuma"
]

needed = {
    "Archuleta":2, "Bent":4, "Cheyenne":3, "Costilla":4, "Elbert":6,
    "Gunnison":3, "Huerfano":5, "Lake":5, "Mineral":2, "Ouray":2,
    "Park":6, "Phillips":3, "Routt":2, "Saguache":4,
    "San Juan":3, "Teller":1, "Washington":5, "Yuma":13
}

regions = {
    "Western": ["Gunnison","Ouray","San Juan","Routt"],
    "Southern": ["Costilla","Huerfano","Saguache","Archuleta","Mineral"],
    "Plains" : ["Bent","Cheyenne","Phillips","Washington","Yuma"],
    "Central": ["Elbert","Lake","Park","Teller"]
}

cost_per_charger = 900000
budget = 57100000


# Region fairness (Min proportion of budget each region is entitled to)
min_region_percent = 0.10

# How much we inflate demand for numerical experiment
demand_inflation = 1.15

for county in needed.keys():
  needed[county] = math.ceil(demand_inflation * needed[county])

In [ ]:
# ----------------------------
# MODEL
# ----------------------------
m = gp.Model("Colorado_EV_Planning with 15% higher demand")

# Decision variables: x[c] = number of chargers built in county c
x = m.addVars(counties, vtype=GRB.INTEGER, name="x", lb=0)

# ----------------------------
# Objective: maximize satisfied demand
# ----------------------------
m.setObjective(gp.quicksum(x[c] for c in counties), GRB.MAXIMIZE)


# ============================
# CONSTRAINT 1: Budget
# ============================
m.addConstr(gp.quicksum(cost_per_charger * x[c]
                        for c in counties) <= budget, "Budget")


# ============================
# CONSTRAINT 2: County minimum and maximum
# (example: at least 0, at most the demand)
# ============================
for c in counties:
    m.addConstr(x[c] <= needed[c], name=f"MaxInCounty[{c}]")
    m.addConstr(x[c] >= 0, name=f"MinInCounty[{c}]")


# ============================
# CONSTRAINT 3: Regional fairness constraints
# Each region must receive at least a fraction of total investment
# ============================
total_spend = gp.quicksum(cost_per_charger * x[c] for c in counties)

for r, rcounties in regions.items():
    m.addConstr(
        gp.quicksum(cost_per_charger * x[c] for c in rcounties)
        >= min_region_percent * total_spend,
        name=f"RegionMinSpend[{r}]"
    )


# ============================
# CONSTRAINT 4: County fairness constraints
# Each county must receive at least one charging station
# ============================
m.addConstrs((x[c] >= 1 for c in counties), name="AtLeastOne")



# Solve
m.optimize()

# Print results
print("\nOptimal number of charging stations with one fast charger to build per county:\n")
print(f"{'County':<15}{'Stations':<10}{'Cost':<15} \n")
for c in counties:
    print(f"{c:<15}{int(x[c].X):<10}${x[c].X * cost_per_charger:,.0f}")

print(f"\nTotal number of charging stations with one fast charger to build: {m.objVal:,.0f}")
print(f"Total cost of building charging stations: $ {m.objVal * cost_per_charger:,.0f}")

Gurobi Optimizer version 13.0.0 build v13.0.0rc1 (linux64 - "Ubuntu 22.04.4 LTS")

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 59 rows, 18 columns and 144 nonzeros (Max)
Model fingerprint: 0x1ff118e5
Model has 18 linear objective coefficients
Variable types: 0 continuous, 18 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 9e+05]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 6e+07]
Presolve removed 54 rows and 14 columns
Presolve time: 0.00s
Presolved: 5 rows, 4 columns, 20 nonzeros
Variable types: 0 continuous, 4 integer (0 binary)
Found heuristic solution: objective 40.0000000
Found heuristic solution: objective 46.0000000

Root relaxation: objective 6.344444e+01, 4 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   63.44444    0    2   46.00000   63.44444  37.9%     -    0s
H    0     0                      63.0000000   63.44444  0.71%     -    0s
     0     0   63.44444    0    2   63.00000   63.44444  0.71%     -    0s

Explored 1 nodes (4 simplex iterations) in 0.02 seconds (0.00 work units)
Thread count was 2 (of 2 available processors)

Solution count 3: 63 46 40

Optimal solution found (tolerance 1.00e-04)
Best objective 6.300000000000e+01, best bound 6.300000000000e+01, gap 0.0000%

Optimal number of charging stations with one fast charger to build per county:

County         Stations  Cost

Archuleta      1         $900,000
Bent           1         $900,000
Cheyenne       1         $900,000
Costilla       1         $900,000
Elbert         7         $6,300,000
Gunnison       4         $3,600,000
Huerfano       1         $900,000
Lake           6         $5,400,000
Mineral        1         $900,000
Ouray          3         $2,700,000
Park           7         $6,300,000
Phillips       1         $900,000
Routt          3         $2,700,000
Saguache       5         $4,500,000
San Juan       4         $3,600,000
Teller         2         $1,800,000
Washington     1         $900,000
Yuma           14        $12,600,000

Total number of charging stations with one fast charger to build: 63
Total cost of building charging stations: $ 56,700,000

In [ ]:
# Prepare data for table to save
results1_data = []
for c in counties:
    optimized_chargers = x[c].X
    county_demand = needed[c] # Use the 'needed' that was updated by VoOD_p4qrt7Q
    county_total_cost = optimized_chargers * cost_per_charger
    results1_data.append({
        "County": c,
        "Demand": county_demand,
        "Optimized Chargers": optimized_chargers,
        "Total Cost": county_total_cost
    })

results1_df = pd.DataFrame(results1_data)


# Save Results DF
results1_df.to_csv('/content/drive/MyDrive/Opt Modeling/Project/experiment1.csv', index=False)

### 2. Model again where region fairness constraint is higher (20%)

In [ ]:
import math

# ----------------------------
# DATA
# ----------------------------

counties = [
    "Archuleta","Bent","Cheyenne","Costilla","Elbert","Gunnison","Huerfano",
    "Lake","Mineral","Ouray","Park","Phillips","Routt","Saguache",
    "San Juan","Teller","Washington","Yuma"
]

needed = {
    "Archuleta":2, "Bent":4, "Cheyenne":3, "Costilla":4, "Elbert":6,
    "Gunnison":3, "Huerfano":5, "Lake":5, "Mineral":2, "Ouray":2,
    "Park":6, "Phillips":3, "Routt":2, "Saguache":4,
    "San Juan":3, "Teller":1, "Washington":5, "Yuma":13
}

regions = {
    "Western": ["Gunnison","Ouray","San Juan","Routt"],
    "Southern": ["Costilla","Huerfano","Saguache","Archuleta","Mineral"],
    "Plains" : ["Bent","Cheyenne","Phillips","Washington","Yuma"],
    "Central": ["Elbert","Lake","Park","Teller"]
}

cost_per_charger = 900000
budget = 57100000

# Region fairness (Min proportion of budget each region is entitled to)
min_region_percent = 0.20

In [ ]:
# ----------------------------
# MODEL
# ----------------------------
m = gp.Model("Colorado_EV_Planning with higher fairness constraint")

# Decision variables: x[c] = number of chargers built in county c
x = m.addVars(counties, vtype=GRB.INTEGER, name="x", lb=0)

# ----------------------------
# Objective: maximize satisfied demand
# ----------------------------
m.setObjective(gp.quicksum(x[c] for c in counties), GRB.MAXIMIZE)


# ============================
# CONSTRAINT 1: Budget
# ============================
m.addConstr(gp.quicksum(cost_per_charger * x[c]
                        for c in counties) <= budget, "Budget")


# ============================
# CONSTRAINT 2: County minimum and maximum
# (example: at least 0, at most the demand)
# ============================
for c in counties:
    m.addConstr(x[c] <= needed[c], name=f"MaxInCounty[{c}]")
    m.addConstr(x[c] >= 0, name=f"MinInCounty[{c}]")


# ============================
# CONSTRAINT 3: Regional fairness constraints
# Each region must receive at least a fraction of total investment
# ============================
total_spend = gp.quicksum(cost_per_charger * x[c] for c in counties)

for r, rcounties in regions.items():
    m.addConstr(
        gp.quicksum(cost_per_charger * x[c] for c in rcounties)
        >= min_region_percent * total_spend,
        name=f"RegionMinSpend[{r}]"
    )


# ============================
# CONSTRAINT 4: County fairness constraints
# Each county must receive at least one charging station
# ============================
m.addConstrs((x[c] >= 1 for c in counties), name="AtLeastOne")



# Solve
m.optimize()

# Print results
print("\nOptimal number of charging stations with one fast charger to build per county:\n")
print(f"{'County':<15}{'Stations':<10}{'Cost':<15} \n")
for c in counties:
    print(f"{c:<15}{int(x[c].X):<10}${x[c].X * cost_per_charger:,.0f}")

print(f"\nTotal number of charging stations with one fast charger to build: {m.objVal:,.0f}")
print(f"Total cost of building charging stations: $ {m.objVal * cost_per_charger:,.0f}")

Gurobi Optimizer version 13.0.0 build v13.0.0rc1 (linux64 - "Ubuntu 22.04.4 LTS")

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 59 rows, 18 columns and 144 nonzeros (Max)
Model fingerprint: 0xcb991f13
Model has 18 linear objective coefficients
Variable types: 0 continuous, 18 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 9e+05]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 6e+07]
Presolve removed 55 rows and 14 columns
Presolve time: 0.00s
Presolved: 4 rows, 4 columns, 16 nonzeros
Variable types: 0 continuous, 4 integer (0 binary)
Found heuristic solution: objective 20.0000000
Found heuristic solution: objective 25.0000000

Root relaxation: objective 5.000000e+01, 3 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0      50.0000000   50.00000  0.00%     -    0s

Explored 1 nodes (3 simplex iterations) in 0.03 seconds (0.00 work units)
Thread count was 2 (of 2 available processors)

Solution count 3: 50 25 20

Optimal solution found (tolerance 1.00e-04)
Best objective 5.000000000000e+01, best bound 5.000000000000e+01, gap 0.0000%

Optimal number of charging stations with one fast charger to build per county:

County         Stations  Cost

Archuleta      1         $900,000
Bent           1         $900,000
Cheyenne       1         $900,000
Costilla       1         $900,000
Elbert         6         $5,400,000
Gunnison       3         $2,700,000
Huerfano       5         $4,500,000
Lake           5         $4,500,000
Mineral        1         $900,000
Ouray          2         $1,800,000
Park           6         $5,400,000
Phillips       1         $900,000
Routt          2         $1,800,000
Saguache       4         $3,600,000
San Juan       3         $2,700,000
Teller         1         $900,000
Washington     1         $900,000
Yuma           6         $5,400,000

Total number of charging stations with one fast charger to build: 50
Total cost of building charging stations: $ 45,000,000

In [ ]:
# Prepare data for table to save
results2_data = []
for c in counties:
    optimized_chargers = x[c].X
    county_demand = needed[c]
    county_total_cost = optimized_chargers * cost_per_charger
    results2_data.append({
        "County": c,
        "Demand": county_demand,
        "Optimized Chargers": optimized_chargers,
        "Total Cost": county_total_cost
    })

results2_df = pd.DataFrame(results2_data)

# Save Results DF
results2_df.to_csv('/content/drive/MyDrive/Opt Modeling/Project/experiment2.csv', index=False)

### 3. Model again where minimum station allocation per county is 0 instead of 1

In [ ]:
import math

# ----------------------------
# DATA
# ----------------------------

counties = [
    "Archuleta","Bent","Cheyenne","Costilla","Elbert","Gunnison","Huerfano",
    "Lake","Mineral","Ouray","Park","Phillips","Routt","Saguache",
    "San Juan","Teller","Washington","Yuma"
]

needed = {
    "Archuleta":2, "Bent":4, "Cheyenne":3, "Costilla":4, "Elbert":6,
    "Gunnison":3, "Huerfano":5, "Lake":5, "Mineral":2, "Ouray":2,
    "Park":6, "Phillips":3, "Routt":2, "Saguache":4,
    "San Juan":3, "Teller":1, "Washington":5, "Yuma":13
}

regions = {
    "Western": ["Gunnison","Ouray","San Juan","Routt"],
    "Southern": ["Costilla","Huerfano","Saguache","Archuleta","Mineral"],
    "Plains" : ["Bent","Cheyenne","Phillips","Washington","Yuma"],
    "Central": ["Elbert","Lake","Park","Teller"]
}

cost_per_charger = 900000
budget = 57100000

# Region fairness (Min proportion of budget each region is entitled to)
min_region_percent = 0.10

In [ ]:
# ----------------------------
# MODEL
# ----------------------------
m = gp.Model("Colorado_EV_Planning with different minimum allocation")

# Decision variables: x[c] = number of chargers built in county c
x = m.addVars(counties, vtype=GRB.INTEGER, name="x", lb=0)

# ----------------------------
# Objective: maximize satisfied demand
# ----------------------------
m.setObjective(gp.quicksum(x[c] for c in counties), GRB.MAXIMIZE)


# ============================
# CONSTRAINT 1: Budget
# ============================
m.addConstr(gp.quicksum(cost_per_charger * x[c]
                        for c in counties) <= budget, "Budget")


# ============================
# CONSTRAINT 2: County minimum and maximum
# (example: at least 0, at most the demand)
# ============================
for c in counties:
    m.addConstr(x[c] <= needed[c], name=f"MaxInCounty[{c}]")
    m.addConstr(x[c] >= 0, name=f"MinInCounty[{c}]")


# ============================
# CONSTRAINT 3: Regional fairness constraints
# Each region must receive at least a fraction of total investment
# ============================
total_spend = gp.quicksum(cost_per_charger * x[c] for c in counties)

for r, rcounties in regions.items():
    m.addConstr(
        gp.quicksum(cost_per_charger * x[c] for c in rcounties)
        >= min_region_percent * total_spend,
        name=f"RegionMinSpend[{r}]"
    )


# ============================
# CONSTRAINT 4: County fairness constraints
# Each county must receive at least one charging station
# (Modified for this experiment to be x[c] >= 0)
# ============================
m.addConstrs((x[c] >= 0 for c in counties), name="AtLeastOne")



# Solve
m.optimize()

# Print results
print("\nOptimal number of charging stations with one fast charger to build per county:\n")
print(f"{'County':<15}{'Stations':<10}{'Cost':<15} \n")
for c in counties:
    print(f"{c:<15}{int(x[c].X):<10}${x[c].X * cost_per_charger:,.0f}")

print(f"\nTotal number of charging stations with one fast charger to build: {m.objVal:,.0f}")
print(f"Total cost of building charging stations: $ {m.objVal * cost_per_charger:,.0f}")

Gurobi Optimizer version 13.0.0 build v13.0.0rc1 (linux64 - "Ubuntu 22.04.4 LTS")

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 59 rows, 18 columns and 144 nonzeros (Max)
Model fingerprint: 0x48fa1e04
Model has 18 linear objective coefficients
Variable types: 0 continuous, 18 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 9e+05]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 6e+07]
Found heuristic solution: objective -0.0000000
Presolve removed 54 rows and 14 columns
Presolve time: 0.00s
Presolved: 5 rows, 4 columns, 20 nonzeros
Variable types: 0 continuous, 4 integer (0 binary)

Root relaxation: objective 6.344444e+01, 5 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   63.44444    0    1   -0.00000   63.44444      -     -    0s
H    0     0                      63.0000000   63.44444  0.71%     -    0s
     0     0   63.44444    0    1   63.00000   63.44444  0.71%     -    0s

Explored 1 nodes (5 simplex iterations) in 0.02 seconds (0.00 work units)
Thread count was 2 (of 2 available processors)

Solution count 2: 63 -0

Optimal solution found (tolerance 1.00e-04)
Best objective 6.300000000000e+01, best bound 6.300000000000e+01, gap 0.0000%

Optimal number of charging stations with one fast charger to build per county:

County         Stations  Cost

Archuleta      2         $1,800,000
Bent           0         $-0
Cheyenne       3         $2,700,000
Costilla       4         $3,600,000
Elbert         6         $5,400,000
Gunnison       3         $2,700,000
Huerfano       5         $4,500,000
Lake           5         $4,500,000
Mineral        2         $1,800,000
Ouray          2         $1,800,000
Park           6         $5,400,000
Phillips       3         $2,700,000
Routt          2         $1,800,000
Saguache       4         $3,600,000
San Juan       3         $2,700,000
Teller         1         $900,000
Washington     0         $-0
Yuma           12        $10,800,000

Total number of charging stations with one fast charger to build: 63
Total cost of building charging stations: $ 56,700,000

In [ ]:
# Prepare data for table to save
results3_data = []
for c in counties:
    optimized_chargers = x[c].X
    county_demand = needed[c]
    county_total_cost = optimized_chargers * cost_per_charger
    results3_data.append({
        "County": c,
        "Demand": county_demand,
        "Optimized Chargers": optimized_chargers,
        "Total Cost": county_total_cost
    })

results3_df = pd.DataFrame(results3_data)

# Save Results DF
results3_df.to_csv('/content/drive/MyDrive/Opt Modeling/Project/experiment3.csv', index=False)

display(results3_df)

        County  Demand  Optimized Chargers  Total Cost
0    Archuleta       2                 2.0   1800000.0
1         Bent       4                -0.0        -0.0
2     Cheyenne       3                 3.0   2700000.0
3     Costilla       4                 4.0   3600000.0
4       Elbert       6                 6.0   5400000.0
5     Gunnison       3                 3.0   2700000.0
6     Huerfano       5                 5.0   4500000.0
7         Lake       5                 5.0   4500000.0
8      Mineral       2                 2.0   1800000.0
9        Ouray       2                 2.0   1800000.0
10        Park       6                 6.0   5400000.0
11    Phillips       3                 3.0   2700000.0
12       Routt       2                 2.0   1800000.0
13    Saguache       4                 4.0   3600000.0
14    San Juan       3                 3.0   2700000.0
15      Teller       1                 1.0    900000.0
16  Washington       5                -0.0        -0.0
17        Yuma      13                12.0  10800000.0